### ISSUE TITLE
Extra prompt symbol

### ISSUE THREAD

**Issue by Qquanwei** [abicky/nodejs-repl.el#15]
![image](https://user-images.githubusercontent.com/9263655/34145771-6590e948-e4d2-11e7-917c-24dbe17e3077.png)

**Comment by Qquanwei** [comment]
when I switch buffer by `C-x o` and come back.

**Comment by abicky** [comment]
Thank you for your report. I confirmed the behavior in the following environment.

* GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.5.0) of 2018-05-29
* v8.11.3

![](https://user-images.githubusercontent.com/508822/45590429-87788400-b973-11e8-9496-358343973636.gif)

**Comment by abicky** [comment]
I've released 0.2.0 including https://github.com/abicky/nodejs-repl.el/pull/21. Please try it.
