### ISSUE TITLE
comint-previous-input breaks repl input

### ISSUE THREAD

**Issue by Wilfred** [abicky/nodejs-repl.el#16]
`M-x nodejs-repl`. then enter an input:

```
> x = 1
1
>
```

Press `M-p` (bound to `comint-previous-input`) causes the buffer to look like this:

```
> x = 1
1
x = 1> 
```

It's then impossible (as far as I can see) to input more text. Pressing RET repeatedly gives this:

```
> x = 1
1
x = 1> x = 1> 
... 
... 
... 
```

**Comment by abicky** [comment]
Is this issue reproducible if you load only nodejs-repl without any customizations? I can't reproduce it.
Please explain more details about your environment.

**Comment by Wilfred** [comment]
I can no longer reproduce this. Sorry.
