### ISSUE TITLE
send to nodejs-repl

### ISSUE THREAD

**Issue by jeroentbt** [abicky/nodejs-repl.el#3]
Could not find a way to send stuff to `nodejs-repl`.
[`repl-toggle-mode`](https://github.com/tomterl/repl-toggle) seems to do the trick nicely

**Comment by abicky** [comment]
I have released nodejs-repl 0.1.0 which supports the feature to send strings to the process.
cf. https://github.com/abicky/nodejs-repl.el/pull/6
